name: Deploy to S3 via Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Invoke Deployment Lambda Function
      env:
        FUNCTION_NAME: GitShowcaseDeployLambda
      run: |
        aws lambda invoke \
          --function-name "$FUNCTION_NAME" \
          --payload '{}' \
          response.json \
          --cli-binary-format raw-in-base64-out

    - name: Show Lambda Response
      run: |
        echo "Lambda Response:"
        cat response.json
